# Generated by Django 3.2 on 2021-12-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20211226_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
