# Generated by Django 3.2 on 2021-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_auto_20211226_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
